# Generated by Django 2.2 on 2022-02-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=246)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('total_experience', models.CharField(blank=True, max_length=30, null=True)),
                ('work_shift', models.CharField(blank=True, choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Signup done On:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
